# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-alerts

extension:
  - url: >-
      http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm'
    valueInteger: 2
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: inm


canonical: 'http://hl7.org/fhir/us/davinci-alerts'
name: DaVinciUnsolicitedNotifications
title: Da Vinci Unsolicited Notifications
status: active
publisher:
  name: HL7 International / Infrastructure And Messaging
  url: 'http://www.hl7.org/Special/committees/inm'
  email: inm@lists.hl7.org 
jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International, all rights reserved Creative Commons License
description: >-
  This implementation guide describes a method for the communication of relevant notifications to support the real-time exchange of information that impacts patient care and value based or risk based services. Providers and Payers may need to be notified when activities occur that impact a patient’s care. This may be as traditional as a notification of an admission or transfer to or discharge from a care setting. It also includes notifications about changes in treatment such as a new or different medication, or changes in patient status like a new diagnosis. These notifications provide information that can improve care management and care coordination as well as act as the trigger for quality programs and other patient focused activities (for example, risk adjustment). By allowing the patient’s healthcare providers to be better informed and able to take actions and intervene earlier, the twin goals of better patient care and reduced cost of care may be met.

license: CC0-1.0
date: 2025-01-07
version: 1.1.0
fhirVersion: 4.0.1

dependencies:

  hl7.fhir.us.core:
    version: 7.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore7
    reason: |
      Needed for systems supporting USCDI v4
  hl7.fhir.us.core.v610:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore6
    reason: |
      Needed for systems supporting USCDI v3
  hl7.fhir.us.core.v311:
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore3
    reason: |
      Needed for systems supporting USCDI v1

  hl7.fhir.us.davinci-hrex:
    uri: 'http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex'
    version: 1.1.0
    id: hrex


groups:
  BaseDaVinciNotificationProfiles:
    name: Base Da Vinci Notification Profiles
    description: These define the base constraints on FHIR resources for systems conforming to this implementation guide. Other Da Vinci Notification Profiles are based on them.
    resources:
      - StructureDefinition/notifications-messageheader
      - StructureDefinition/notifications-bundle

  DaVinciADTNotificationProfiles:
    name: Da Vinci Admission/Discharge/Transfer Notification Profiles
    description: Operations associated with CDex admission/discharge/transfer notifications
    resources:
      - StructureDefinition/admit-notification-messageheader
      - StructureDefinition/discharge-notification-messageheader
      - StructureDefinition/transfer-notification-messageheader
      - StructureDefinition/adt-notification-condition
      - StructureDefinition/adt-notification-coverage
      - StructureDefinition/adt-notification-encounter

  ValueSets:
    name: 'Terminology: Value Sets'
    description: These define sets of codes used by systems conforming to this implementation guide.
    resources:
      - ValueSet/notification-event
      - ValueSet/notification-admit-event
      - ValueSet/notification-discharge-event
      - ValueSet/notification-transfer-event

  CodeSystems:
    name: 'Terminology: Code Systems'
    description: >-
      These define new code systems used by systems conforming to this implementation guide.

      *The code systems defined here are not part of the base FHIR specification and future versions of this guide will migrate them to VSAC or another standard centralized US Realm terminology authority.*
    resources:
      - CodeSystem/notification-event

  BundleExamples:
    name: Bundle Examples 
    description: These are Bundle example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - Bundle/admit-notification-message-bundle-01
      - Bundle/admit-notification-message-bundle-02
      - Bundle/discharge-notification-message-bundle-01
      - Bundle/transfer-notification-message-bundle-01
      - Bundle/admit-notification-intermediate-translate-bundle
      - Bundle/admit-notification-intermediate-transmit-bundle

  # ConditionExamples:
  #   name: Condition Examples 
  #   description: These are Condition example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
  #   resources:
  #     - Condition/adt-notification-condition-01

  # CoverageExamples:
  #   name: Coverage Examples 
  #   description: These are Coverage example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
  #   resources:
  #     - Coverage/adt-notification-coverage-01

  # EncounterExamples:
  #   name: Encounter Examples 
  #   description: These are Encounter example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
  #   resources:
  #     - Encounter/adt-notification-encounter-01

  # MessageHeaderExamples:
  #   name: MessageHeader Examples 
  #   description: These are MessageHeader example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
  #   resources:
  #     - MessageHeader/admit-notification-messageheader-01
  #     - MessageHeader/admit-notification-messageheader-02
  #     - MessageHeader/discharge-notification-messageheader-01
  #     - MessageHeader/transfer-notification-messageheader-01

  CapabilityStatement:
    name: CapabilityStatements 
    description: |-
     There are **3 Capability Statements** defining computable definitions of FHIR conformance expectations of the RESTful transactions and specific profiles for each of the Da Vinci Notification Roles. They provide the base conformance rules that may be used for system compatibility testing, code generation, or as the basis for a conformance assessment.

     The following table summarizes how these CapabilityStatements applies to the Da Vinci Notification Roles

      |Role|server-mode|client-mode|
      | --- | :---: | :---: |
      |Sender |-| Da Vinci Notification Sender|
      |Intermediary |Da Vinci Notification Receiver| Da Vinci Notification Forwarder|
      |Recipient |Da Vinci Notification Receiver |-|
      {: .grid}
    resources:
      - CapabilityStatement/notification-sender
      - CapabilityStatement/notification-receiver
      - CapabilityStatement/notification-forwarder

pages:
  index.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Home
  # exchanging.md:
  #   extension:
  #   - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
  #     valueCode: informative
  #   title: Architectural Approach
  scope.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Scope and Usage
  roles.md: 
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Roles and Actors
  workflow.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Workflow
  guidance.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Framework
  usecases.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Admit/Discharge/Transfer Use Case
  security.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Privacy, Safety, and Security
  downloads.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Downloads
  changes.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Change Log
  ImplementationGuide-hl7.fhir.us.davinci-alerts.md:
    title: Unsolicited Notification ImplementationGuide Resource
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'  # for using US ed of SNOMED
  path-data: 
    - input/resources-yaml
  active-tables: false
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  apply-version: true
  show-inherited-invariants: true
  usage-stats-opt-out: true
  # excludexml: false
  # excludejson: false
  # excludettl: true
  # excludemap: true
  # suppressed-ids: DocumentReference/discharge-summary
  # produce-jekyll-data: true #add all resources to data for access by Jekyll/liquid in pages DOES NOT WORK
  tabbed-snapshots: false
  validation: check-aggregation
  auto-oid-root: '2.16.840.1.113883.4.642.40.47'
  # generate: #what does this do - todo: remove and see4
  #   - xml
  #   - json
  # no-narrative:
  #   - Patient/example-targeted-provenance

  # no-validate:
  #   - 'StructureDefinition/*'
  # version-comparison:
  #    - 1.0.0

  # html-exempt:  # These pages are generated by the cli validator for comparison between Argo and US Core
  #   - comparison-argo/vs-observation-status-us-core-observation-smoking-status-status.html
  # ipa-comparison: 
  #   - '{current}'
copyrightyear: '2024+'
#releaselabel: CI Build
releaselabel: STU 1.1  # for publication
# releaselabel: Ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Background:
    Da Vinci Overview: http://hl7.org/about/davinci
    Da Vinci Guiding Principles: https://hl7.org/fhir/us/davinci-hrex/2024Sep/davinci-guiding-principles.html
    # Architectural Approach: exchanging.html
  Specification:
    Scope and Usage: scope.html
    Roles and Actors: roles.html
    Workflow: workflow.html
    Framework: guidance.html
    Privacy, Safety, and Security: security.html
    Admit/Discharge/Transfer Use Case: usecases.html
  FHIR Artifacts:
    Artifacts Summary: artifacts.html
    Base Da Vinci Notification Profiles: artifacts.html#1
    Da Vinci Admission/Discharge/Transfer Notification Profiles: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4
    Bundle Examples : artifacts.html#5
    Capability Statement : artifacts.html#6
    Concept Maps: artifacts.html#7
  Base Specs:
    FHIR R4 Spec: https://hl7.org/fhir/R4/index.html
    HRex 1.1.0: https://hl7.org/fhir/us/davinci-hrex/STU1.1/index.html
    US Core 3.1.1: https://hl7.org/fhir/us/core/STU3.1.1/index.html
    US Core 6.1.0: https://hl7.org/fhir/us/core/STU6.1/index.html
    US Core 7.0.0: https://hl7.org/fhir/us/core/STU7/index.html
  Support:

   Discussion Forum: https://chat.fhir.org/#narrow/channel/205917-Da-Vinci-Alerts
   Project Page: https://confluence.hl7.org/pages/viewpage.action?pageId=51225442  
   Implementer Support: https://confluence.hl7.org/display/DVP/Notifications+Implementer+Support
   Specification Dashboard: https://jira.hl7.org/secure/Dashboard.jspa?selectPageId=11905
   Propose a Change: https://jira.hl7.org/secure/
   Downloads: downloads.html
  Change Log: changes.html
