# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-alerts

extension:
  - url: >-
      http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm'
    valueInteger: 2
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: inm


canonical: 'http://hl7.org/fhir/us/davinci-alerts'
name: DaVinciUnsolicitedNotifications
title: Da Vinci Unsolicited Notifications
status: active
publisher:
  name: HL7 International / Infrastructure And Messaging
  url: 'http://www.hl7.org/Special/committees/inm'
  email: inm@lists.hl7.org 
jurisdiction: 'urn:iso:std:iso:3166#US'
copyright: >-
  Used by permission of HL7 International, all rights reserved Creative Commons License
description: >-
  This implementation guide describes a method for the communication of relevant notifications to support the real-time exchange of information that impacts patient care and value based or risk based services. Providers and Payers may need to be notified when activities occur that impact a patient’s care. This may be as traditional as a notification of an admission or transfer to or discharge from a care setting. It also includes notifications about changes in treatment such as a new or different medication, or changes in patient status like a new diagnosis. These notifications provide information that can improve care management and care coordination as well as act as the trigger for quality programs and other patient focused activities (for example, risk adjustment). By allowing the patient’s healthcare providers to be better informed and able to take actions and intervene earlier, the twin goals of better patient care and reduced cost of care may be met.

license: CC0-1.0
date: 2024-08-27
version: '1.1.0-preview'
fhirVersion: 4.0.1

dependencies:
  hl7.fhir.us.core.3.1.1:
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore3

  hl7.fhir.us.core:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore

  hl7.fhir.us.davinci-hrex:
    uri: 'http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex'
    version: 1.1.0-ballot
    id: hrex


groups:
  BaseDaVinciNotificationProfiles:
    name: Base Da Vinci Notification Profiles
    description: These define the base constraints on FHIR resources for systems conforming to this implementation guide. Other Da Vinci Notification Profiles are based on them.
    resources:
      - StructureDefinition/notifications-messageheader
      - StructureDefinition/notifications-bundle

  DaVinciADTNotificationProfiles:
    name: Da Vinci Admission/Discharge/Transfer Notification Profiles
    description: Operations associated with CDex admission/discharge/transfer notifications
    resources:
      - StructureDefinition/admit-notification-messageheader
      - StructureDefinition/discharge-notification-messageheader
      - StructureDefinition/transfer-notification-messageheader
      - StructureDefinition/adt-notification-condition
      - StructureDefinition/adt-notification-coverage
      - StructureDefinition/adt-notification-encounter

  ValueSets:
    name: 'Terminology: Value Sets'
    description: These define sets of codes used by systems conforming to this implementation guide.
    resources:
      - ValueSet/notification-event
      - ValueSet/notification-admit-event
      - ValueSet/notification-discharge-event
      - ValueSet/notification-transfer-event

  CodeSystems:
    name: 'Terminology: Code Systems'
    description: >-
      These define new code systems used by systems conforming to this implementation guide.

      *The code systems defined here are not part of the base FHIR specification and future versions of this guide will migrate them to VSAC or another standard centralized US Realm terminology authority.*
    resources:
      - CodeSystem/notification-event

  BundleExamples:
    name: Bundle Examples 
    description: These are Bundle example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - Bundle/admit-notification-message-bundle-01
      - Bundle/discharge-notification-message-bundle-01
      - Bundle/transfer-notification-message-bundle-01
      - Bundle/admit-notification-intermediate-translate-bundle
      - Bundle/admit-notification-intermediate-transmit-bundle

  ConditionExamples:
    name: Condition Examples 
    description: These are Condition example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - Condition/adt-notification-condition-01

  CoverageExamples:
    name: Coverage Examples 
    description: These are Coverage example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - Coverage/adt-notification-coverage-01

  EncounterExamples:
    name: Encounter Examples 
    description: These are Encounter example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - Encounter/adt-notification-encounter-01

  MessageHeaderExamples:
    name: MessageHeader Examples 
    description: These are MessageHeader example instances that show what data produced and consumed by systems conforming with this implementation guide might look like.
    resources:
      - MessageHeader/admit-notification-messageheader-01
      - MessageHeader/admit-notification-messageheader-02
      - MessageHeader/discharge-notification-messageheader-01
      - MessageHeader/transfer-notification-messageheader-01

  CapabilityStatement:
    name: CapabilityStatements 
    description: The following artifacts define the specific capabilities that different types of systems are expected to have in order to comply with this implementation guide. Systems conforming to this implementation guide are expected to declare conformance to one or more of the following capability statements.
    resources:
      - CapabilityStatement/notification-sender
      - CapabilityStatement/notification-receiver
      - CapabilityStatement/notification-forwarder

pages:
  index.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Home
  exchanging.xml:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Architectural Approach
  scope.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Scope and Usage
  roles.md: 
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Roles and Actors
  workflow.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Workflow
  guidance.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Framework
  usecases.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Admit/Discharge/Transfer Use Case
  security.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: trial-use
    title: Security
  downloads.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Downloads
  change-notes.md:
    extension:
    - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
      valueCode: informative
    title: Change Log
  ImplementationGuide-hl7.fhir.us.davinci-alerts.md:
    title: Unsolicited Notification ImplementationGuide Resource
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'  # for using US ed of SNOMED
  active-tables: false
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  apply-version: true
  show-inherited-invariants: true
  usage-stats-opt-out: true
  # excludexml: false
  # excludejson: false
  # excludettl: true
  # excludemap: true
  # suppressed-ids: DocumentReference/discharge-summary
  tabbed-snapshots: false
  validation: check-aggregation
  auto-oid-root: '2.16.840.1.113883.4.642.40.47'
  # generate: #what does this do - todo: remove and see4
  #   - xml
  #   - json
  # no-narrative:
  #   - Patient/example-targeted-provenance

  # no-validate:
  #   - 'StructureDefinition/*'
  # version-comparison:
  #    - 1.0.0

  # html-exempt:  # These pages are generated by the cli validator for comparison between Argo and US Core
  #   - comparison-argo/vs-observation-status-us-core-observation-smoking-status-status.html
  # ipa-comparison: 
  #   - '{current}'
copyrightyear: '2023+'
#releaselabel: CI Build
releaselabel: STU1
# releaselabel: Ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  # Background:
  #   Da Vinci Overview: http://hl7.org/about/davinci
  #   Da Vinci Guiding Principles: https://hl7.org/fhir/us/davinci-hrex/2024Sep/davinci-guiding-principles.html
  #   Architectural Approach: exchanging.html
  # Specification:
  #   Scope and Usage: scope.html
  #   Roles and Actors: roles.html
  #   Workflow: workflow.html
  #   Framework: guidance.html
  #   Security: security.html
  #   Admit/Discharge/Transfer Use Case: usecases.html
  FHIR Artifacts:
    Base Da Vinci Notification Profiles: artifacts.html#1
    Da Vinci Admission/Discharge/Transfer Notification Profiles: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4
    Bundle Examples : artifacts.html#5
    Condition Examples : artifacts.html#5
    Coverage Examples : artifacts.html#6
    Encounter Examples : artifacts.html#7
    MessageHeader Examples : artifacts.html#7
    Capability Statement : artifacts.html#9
  Support:
    Project Home: https://confluence.hl7.org/pages/viewpage.action?pageId=51225442
    Discussion Forum: https://chat.fhir.org/#narrow/stream/179283-Da-Vinci
    Propose a Change: http://hl7.org/fhir-issues
    Downloads: downloads.html
  Change Log: change-notes.html
